### ISSUE TITLE
pycon.cz does not have valid HTTPS cert

### ISSUE THREAD

**Issue by hroncok** [pyvec/cz.pycon.org-2016#11]
If you go to https://pycon.cz/ the certificate it serves is for https://cz.pycon.org/

Found by @petrhodac

**Comment by tricoder42** [comment]
Yes, we have only one cert (for cz.pycon.org). `pycon.cz` should redirect you directly to `cz.pycon.org`. Is that possible even without cert or do we really need a second one for `pycon.cz`?

TLDR: Official PyCon CZ URL is `cz.pycon.org`, `pycon.cz` is borrowed domain and we use it for mailing list only.

**Comment by netman92** [comment]
Yes, we really need a second one. What about using https://letsencrypt.org?

**Comment by hroncok** [comment]
The redirect does not work on https. You'll need a cert for that. You can
have one cetr for both.

**Comment by tricoder42** [comment]
Good point, thank you! I'll see what we can do about it.

**Comment by honzajavorek** [comment]
I guess this is not relevant anymore?

**Comment by hroncok** [comment]
Right. It works now.
