### ISSUE TITLE
Sponsors page content issues

### ISSUE THREAD

**Issue by underyx** [pyvec/cz.pycon.org-2016#117]
On the [sponsors page](https://cz.pycon.org/2016/sponsors/)
- [ ] Based on the copy & logo provided, it feels like instead of _Microsoft_, the sponsoring entity should be called _Microsoft Azure_
- [x] It seems like _Big Shock Energy_ should be _Big Shock!_
- [x] Big Shock's description also has some weird spaces scattered around:
  
  > [...] This fi rst born non-fi zzy variant [...]
- [x] _Sli.do_ should be written as _Slido_ probably, based on text written by the company

cc @kejbaly2

**Comment by calmrat** [comment]
Fixed. Microsoft sent me that logo to use... so... i think we should keep it as is.

**Comment by underyx** [comment]
@kejbaly2 That's exactly what I mean. If they sent that logo, shouldn't the sponsor be called 'Microsoft Azure' instead of 'Microsoft'?
