### ISSUE TITLE
Keynote Proposal - Nicholas H.Tollervey (@ntoll) on "Micro:Bit" or... Python and Education

### ISSUE THREAD

**Issue by calmrat** [pyvec/cz.pycon.org-2016#14]
He gave a talk recently at PyCon SK entitled "Teach, Learn, Python"
  https://www.youtube.com/watch?v=vhP7zjq0XEI
That covers Python, Education and introduces the Micro:Bit.

He's the author of the Mu Code editor for children and beginner programmers
  A "micro" editor for MicroPython and the BBC micro:bit. Written in Python and Qt5. 
  http://codewith.mu/

He recently wrote a book on this topic called "Python in Education":
  http://www.oreilly.com/programming/free/python-in-education.csp

And does lots of presentations: 
  http://ntoll.org/presentations/

I don't yet have an abstract for his talk, but he's interested. He's not 100% sure he'll be able to make it, but if folks agree to invite him, the sooner we can push him an offer the better chance we'll have to get PyCon CZ on his schedule.

Coming from the UK, I would estimate costs to be about 15,000czk

**Comment by kvbik** [comment]
If not for keynote, it would def be a good talk to repeat

**Comment by kvbik** [comment]
cool guy, i spoke with him at pycon.

**Comment by calmrat** [comment]
No more keynote spots available and CfP is closed.
