### ISSUE TITLE
Keynote Proposal - Irit Malka (@iritmalka) or Rony Jacobson on "Girls, Code, Communities"

### ISSUE THREAD

**Issue by calmrat** [pyvec/cz.pycon.org-2016#15]
I met Irit Malka and Rony Jocobson at DjangoGirls. They are both Pythonista's and co-founders of the incredible fast growing SheCodes organization http://www.she-codes.org . 

I was deeply impressed with their work. In less than 3 years they have taken an idea to help women of Isreal learn to code from zero to more than 10,000+ active learners! How? Well, based on my discussions with them they're taking a pretty novel approach. Personally, I was inspired and believe we could learn a lot from them about building strong communities of passion like they have done with women and programming in Israel. 

I've asked Irit first if she'd be interested in Keynoting PyCon CZ. She'd interested but not sure yet about timing. If she couldn't do it, Rony said she'd consider too. I don't have an abstract yet of what they might speak of, but I've suggested we'd like to hear the secrets of repeating the launch of such a successful community as SheCodes has become. I should know in the coming couple of weeks if they could make it.

In the mean time, I'd like to hear feedback from folks on this keynote idea.

Again, coming from Israel, I estime costs for flight and 3 nights accomodation to be around 16,000czk total (for one person)

**Comment by kvbik** [comment]
I love it. Would be awesome to have them there.

**Comment by calmrat** [comment]
Irit say's she can't make it, but i'm trying to connect with other founders and leaders in SheCodes

**Comment by calmrat** [comment]
ACCEPTED. But it will be a different representative from SheCodes, Lea Polachek.
