### ISSUE TITLE
Workshop Venue Selection Alternatives

### ISSUE THREAD

**Issue by calmrat** [pyvec/cz.pycon.org-2016#16]
ImpactHub was last year's choice as the PyCon 15 Workshop Venue. 

Days: 1
Capacity: 200 (divadlo) or maybe 80 with tables
Cost: 21,000czk
Location: Cyrilská 7, Brno

As we expect PyCon CZ to be larger this year, we're looking for alternative locations for workshops to consider.

Requirements:
When: October 30
Open:  8:00
Close: 18:00
Capacity, with tables: 150
Location: Brno, City Center
Cost: Depends...

**Comment by petrjoachim** [comment]
Is it supposed to have one large room with one workshop topic or more smaller rooms?

**Comment by calmrat** [comment]
Let's assume branching into separate, smaller rooms is acceptable as well
as one large room.

**Comment by tricoder42** [comment]
Going to take VUT FIT as well
