### ISSUE TITLE
Call for papers - Article

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2016#18]
Write a short article about our Call for papers. Mention we aim for high diversity of topics and speakers, which topics we prefer, important dates and what speakers get covered. Try to encourage everyone including  beginners and people out of field (python) who still can contribute to our community.

Examples:
[JS Conf 2015](https://github.com/jsconf/2015.jsconf.eu/blob/gh-pages/call-for-speakers.md)

**Comment by calmrat** [comment]
First draft

https://docs.google.com/document/d/1NULGuW-MpwZ5M3RLusUIfSeV7W2e1M4H8mG4w1wzny4/edit#
