### ISSUE TITLE
Code of  Conduct - Review

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2016#19]
Review our code of conduct and find out if we want to add/remove/change something.

https://github.com/pyvec/cz.pycon.org-2015/blob/master/code-of-conduct.md

**Comment by tricoder42** [comment]
Find a better shortcut for `Code of Conduct` than `COC`.

Some alternatives: `code`, `conduct`, `codex`?

**Comment by Luminaar** [comment]
Here is a document that contains more info about the CoC: https://drive.google.com/open?id=1m6NEBoThnzzuZBA47n_LH2kbWpdbkIqdxfReW0U-B_o

**Comment by Luminaar** [comment]
Please review the code of [conduct and the procedure for the attendees](https://docs.google.com/document/d/1a2eedo6RV7ikaWtJIVxial802IOUZ64Z9TKRhCS0muw/edit?usp=sharing)

**Comment by calmrat** [comment]
I think we should keep it as CoC.  Yes sure it can be made fun of
easily,but still, it's the commonly used abbreviation for it

**Comment by encukou** [comment]
I think we should just use the full term, "Code of Conduct", everywhere.

**Comment by Luminaar** [comment]
I agree that we should keep the name and just use the full version.

**Comment by Luminaar** [comment]
Please review and proofread the [czech version of the Code of Conduct](https://docs.google.com/document/d/1a2eedo6RV7ikaWtJIVxial802IOUZ64Z9TKRhCS0muw/edit?usp=sharing)
