### ISSUE TITLE
Mandatory registration for workshops

### ISSUE THREAD

**Issue by encukou** [pyvec/cz.pycon.org-2016#2]
We need to know the number of people in advance

**Comment by honzajavorek** [comment]
@encukou Is this fulfilled?

**Comment by calmrat** [comment]
Any thoughts on this for this year's event!?

**Comment by tricoder42** [comment]
Not sure. 64 people is capacity for each workshop. We might setup simple registration form

**Comment by tricoder42** [comment]
Good old pencil & paper
