### ISSUE TITLE
About the conference

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2016#20]
Write a short article about PyCon CZ, what we aim for, what's our goal and what's our conference about.

Highlight few paragraphs, which could be used on a homepage as well, especially:
- claim (one or two sentences describing PyCon CZ, probably our goal which already wrote @kejbaly2)
- description (one paragraph with more verbose description - python, Brno, cakes, something lovely 😼 )

**Comment by calmrat** [comment]
I'll start with the About PyCon CZ: comments/edits in-doc, please

https://docs.google.com/document/d/1mRwrd0I_tHT-QWPT7l4wuq6Q7ZtswL55R6ZypHBZElM/edit#
