### ISSUE TITLE
Distribute maps

### ISSUE THREAD

**Issue by encukou** [pyvec/cz.pycon.org-2016#3]
- Promote all the good places to go in Brno
- Let people know where the sprints venue is

**Comment by honzajavorek** [comment]
We can probably directly distribute https://www.use-it.travel/cities/detail/brno/ and http://brnonow.com/. The guide is 160 CZK, so maybe we could buy it just to a limited number of visitors (speakers?). We could alter USE-IT maps distributed by us by marking our venues on it (using hand & marker).

**Comment by encukou** [comment]
I suppose we could even work with the USE-IT team to get a special version for the conference. 
The big guide is probably overkill for most visitors.

**Comment by honzajavorek** [comment]
Yes, the maintainers of the Brno version can be found somewhere on website
of the Czech branch of USE-IT.

The guide is definitely an overkill, useful maybe from someone coming from
distant places, who spends there at least couple of days. What came to my
mind - Kasparek could prepare something special for us as well. He could
curate one paper/page on our site with tips useful exactly for someone like
our visitors and we would just pay for the work and print it ourselves.

Just an idea. 💡

**Comment by tricoder42** [comment]
Closed in favor of #6
