### ISSUE TITLE
Spin up an app which does auto-invites to Slack

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/cz.pycon.org-2016#46]
Similar to this: https://github.com/apiaryio/api-blueprint/#api-design-for-humans

**Comment by tricoder42** [comment]
Do you want to auto-invite all attendees to Pyvec slack? Or do you want to create a new, PyCon CZ 2016 slack, like it was on last DjangoCon Europe and Django Under the Hood?

**Comment by honzajavorek** [comment]
@tricoder42 I'd make it optional. I'm not sure conference Slacks proved to be very useful, but your experience might be different. I seen several conference-dedicated Slacks and there were just 100 "hi" messages. So I'd leave it optional.

I want auto-invite app mainly generally for anyone interested in joining the Pyvec Slack. I'd promote the option to join us there towards both Czech Python community and PyCon attendees and leave it up to them if they want to join or what.

But if attendees will be encouraged in any way to join, we should rename `#pycon` to `#pycon-orgs` or sth like that and leave `#pycon` to attendees. Just thinking out loud.

**Comment by tricoder42** [comment]
Yeah, I would make different Slack for attendees and leave Pyvec slack for organizers / people interested in Czech Python community only. If we include the link to auto-invite app somewhere, just make it clear, that it’s not PyCon CZ 2016 slack :) I wouldn’t definitely create #pycon & #pycon-orgs in one Slack.

**Comment by tricoder42** [comment]
Closing, the auto invite app didn't work, so we switched to hangouts...
