### ISSUE TITLE
Add OpenGraph tags

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/cz.pycon.org-2016#48]
Image (logo?) isn't displayed correctly on FB:

<img width="506" alt="screen shot 2016-08-02 at 20 24 20" src="https://cloud.githubusercontent.com/assets/283441/17340111/27d61f76-58ef-11e6-8b3b-e09323e03941.png">

Debugger:

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fcz.pycon.org%2F2016%2Fproposals%2Ftalks%2Fform

**Comment by tricoder42** [comment]
Actually, we don't have OpenGraph tags at all. Volunteer? :)

**Comment by tricoder42** [comment]
# Description

Add relevant OpenGraph tags to `head` section in `pyconcz_2016/templates/_base.html`.

Most of tags can Facebook detect automatically, but some of them not (like `og:image`).
<img width="511" alt="snimek obrazovky 2016-08-04 v 9 40 35" src="https://cloud.githubusercontent.com/assets/827862/17394106/b0208eb4-5a27-11e6-9249-d84ba05b78c7.png">

`og:image` should be set to PyCon CZ 2016 logo

**Comment by Luminaar** [comment]
I'm on it.
