### ISSUE TITLE
Link to tickets is public, but broken

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/cz.pycon.org-2016#49]
"Early Bird and Student discounts"

https://cz.pycon.org/2016/about

<img width="295" alt="screen shot 2016-08-02 at 21 39 36" src="https://cloud.githubusercontent.com/assets/283441/17342460/a75d5458-58f9-11e6-821d-9a0166923a8a.png">

---

Discovered by @starenka

**Comment by tricoder42** [comment]
Fixed, thanks! :)
