### ISSUE TITLE
[Epic] Essential website content

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2016#57]
Site navigation sketch:
<img width="1169" alt="snimek obrazovky 2016-08-10 v 9 59 12" src="https://cloud.githubusercontent.com/assets/827862/17546177/20becaec-5ee1-11e6-8af0-805f1d3a513f.png">
- Homepage (add basic info, tweets from last year)
- About #20 
  - Team #63 
  - Sponsors #36 
  - Tickets
  - Financial Aid #24 
  - Code of conduct #19 
- Getting here
  - Travelling - how to get to Brno (might be taken from last year)
  - Accomodation - where to stay (might be taken from last year)
  - Getting around Brno - Kasparek's guide? https://github.com/pyvec/cz.pycon.org-2016/issues/71
- Agenda
  - Call for papers #18 
  - Speakers - directory of all speakers and lecturers
  - Talks - schedule of talks
  - Workshops - schedule of workshops and sprints
  - PyConTest - (optional) are we doint pycontest this year?
  - Social Events - Info about (after|before)-parties

**Comment by honzajavorek** [comment]
I'll take care of "Getting around Brno".

**Comment by tricoder42** [comment]
Looks it's all ready!
