### ISSUE TITLE
Printed booklets

### ISSUE THREAD

**Issue by encukou** [pyvec/cz.pycon.org-2016#6]
Some attendees prefer having a piece of paper in their hands.

Perhaps bring a printer and print these on demand?

**Comment by netman92** [comment]
Absolutely agree with the printer. There was a lot of things to print.

**Comment by tricoder42** [comment]
Create printed booklet with all useful information:
- introduction about the conference
- schedule of all days
- speakers bio and talk abstracts
- sponsors
- social events
- what can be done/seen in Brno (related #3)
- games or fun stuff :)

**Comment by honzajavorek** [comment]
Related to #71

**Comment by calmrat** [comment]
Who's responsible for this this year? Did we get a name assigned to this task for this year?

**Comment by tricoder42** [comment]
Trixi is working on design, we need to find somebody who prepare the content

**Comment by calmrat** [comment]
Are you on finding someone? Should start it this week still...

**Comment by tricoder42** [comment]
We're skipping this, right? All info will be on lanyards
