### ISSUE TITLE
Submissions should support 'multiple speakers'

### ISSUE THREAD

**Issue by calmrat** [pyvec/cz.pycon.org-2016#65]
https://twitter.com/nischalhp/status/764863531887886336

**Comment by calmrat** [comment]
From the tweet above: "@pyconcz I have submitted a proposal but I need to add an additional speaker, is that possible? #pyconcz #keepingfingerscrossed"

**Comment by tricoder42** [comment]
Let's handle it like last year… Comma Separated Names
