### ISSUE TITLE
PyCon CZ CfP Poster

### ISSUE THREAD

**Issue by calmrat** [pyvec/cz.pycon.org-2016#67]
Something simple but to the point; include a QRcode and important dates. Needs to be ready by Monday, latest I think, to be of much use... Sorry for the late notice!

**Comment by beatrix-bodo** [comment]
Is this an actual poster or something for web? What are the dimensions? Thanks!

**Comment by tricoder42** [comment]
A3 would be enough :) Thank you!

**Comment by honzajavorek** [comment]
CfP is over and we have #83 for general purpose poster.
