### ISSUE TITLE
Promotion (CZ) text for CfP

### ISSUE THREAD

**Issue by calmrat** [pyvec/cz.pycon.org-2016#69]
could you prepare me a short write-up about PyCon CZ CfP; I think i can get it published on root.cz, mojefedora.cz and a few other places like that

**Comment by calmrat** [comment]
Promote over at https://www.facebook.com/groups/pyonieri/?fref=nf too

**Comment by honzajavorek** [comment]
I scheduled some tweets related to CfP today. I still don't have the invitation text ready though. When it's ready, I might ask for help with following contact list:
- [x] get cfp published at
  - [x] root.cz
  - [x] zdrojak.cz
  - [x] abclinuxu.cz
  - [x] linuxsoft.cz
  - [x] linuxexpres.cz
- [ ] write to various user groups to promote our cfp:
  - [x] pyconpl
  - [x] pycon ukraine
  - [x] pyconsk
  - [x] rubyslava
  - [ ] pyugat 
  - [ ] vienna.rb
  - [ ] pykonik
  - [ ] pysilesia
  - [ ] devconf?
  - [ ] openalt?
  - [x] prague ruby meetups
  - [x] czechitas - koucove
  - [ ] something in hungary??
  - [ ] something in slovenia??
  - [ ] something in belgium??
  - [ ] something in ...??
  - [ ] ...?
- [x] reach at least some university teachers with cfp
  - [x] ostrava
  - [x] fit brno
  - [x] fit praha
  - [x] muni
  - [ ] olomouc
- [x] write to the FB event
- [x] post to pyonieri, django-cs, py.cz again later on

**Comment by tricoder42** [comment]
CFP is over, can we close it now?

**Comment by honzajavorek** [comment]
Yup.
