### ISSUE TITLE
Make sure the website is complete in time and the structure is understandable

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/cz.pycon.org-2016#7]
- how to find venue, contact, schedule, food, accommodation tips, etc.
- full descriptions of talks!

**Comment by calmrat** [comment]
We are almost there!!!!!! Still need a few more things though... How to find venue and accomodation tips are missing.

**Comment by calmrat** [comment]
But this is all covered in https://github.com/pyvec/cz.pycon.org-2016/issues/57 so closing
