### ISSUE TITLE
Get list of previous CfP Submitter email's

### ISSUE THREAD

**Issue by calmrat** [pyvec/cz.pycon.org-2016#70]
Could someone please draw up a list of CfP submitter emails and add them to (private) https://docs.google.com/spreadsheets/d/1DlMEyVyLFqxcfeeat8pbqKMUENtlr-Q6AdYdR18iRkQ/edit#gid=0 ?

**Comment by tricoder42** [comment]
I've shared a CFP submissions from last year with you (Google Doc). Check you mail 📬
