### ISSUE TITLE
Put Sponsor page in main menu

### ISSUE THREAD

**Issue by calmrat** [pyvec/cz.pycon.org-2016#78]
https://cz.pycon.org/2016/sponsors/offer is a page up already index by google but it can't be reached by the site.... add it to the header please. 

Also, while you're there, include this link in there for folks to downlad the prospectus as well as PDF.

[PyConCZ-PartnerPackagesOverview (2).pdf](https://github.com/pyvec/cz.pycon.org-2016/files/438766/PyConCZ-PartnerPackagesOverview.2.pdf)

**Comment by tricoder42** [comment]
Done! Sorry for delay 😊
