### ISSUE TITLE
Realtime speech to text transcription

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2016#8]
# Goal

Provide realtime speech to text service for all attendees (English). Either only one or both tracks. Use these transcriptions as subtitles in videos.
## Optional

Provide realtime translation to Czech (text only?)
# Providers

I would rather have a human speech2text, than automatic, but YMMW.
## Manual

Already contacted [CZSP CUN](http://www.czsp.cun.cz/index.php?clanek=12) and requested price estimation.
## Automatic

I've heard that in Brno there's some project who does it. Don't have any additional info.

**Comment by honzajavorek** [comment]
Webexpo does this. I can ask Šárka who does this for them.

**Comment by tricoder42** [comment]
Not this year
