### ISSUE TITLE
Video streaming

### ISSUE THREAD

**Issue by petrpulc** [pyvec/cz.pycon.org-2016#81]
In case of video streaming, each room needs in the minimalistic case at least:
## Venue:
- Ethernet connection, at least 4Mbit up
- Power (strip of 3 at least)
### Venue check:
- [ ] Line-level sound output socket type (if any)
## Equipment (I cannot easily provide):
- As powerfull computer as possible:
  - notebook (i7vPro minimum) or tower (Xeon preferred, but desktop i5 should suffice)
  - USB 3.0 (type A) or PCI-E x8 respectively
  - Win 7+ preferred, OSX may not work with USB 3 cards (that I have)
## Equipment (I can most likely provide from AVC ČVUT / SH):
- Capture card 
  - Blackmagic Intensity Shutte (up to 2x) - USB 3.0
  - Blackmagic Mini Recorder (up to 2x) - PCI-E x8 (may work with Linux towers as well, not tested)
- Camcorder
  - Small consumer-grade Panasonic with external sound input (up to 2x)
  - More expensive camcorders with XLR sound input (only in case of adequate funding and huge safety precautions)
- Various tripods
## People:
- 1 technician with good knowledge of Googling and mouse clicking

Such person (+ one backup in ideal case) should be tutored by me as soon as possible - favourable in person in Prague, Hangout possible

**Comment by tricoder42** [comment]
Unfortunatelly, for streaming we need stable LAN, but venue couldn't provide ethernet cable... so we just recorded all talks without streaming.
