### ISSUE TITLE
POST EVENT - Sponsor Summary Reports

### ISSUE THREAD

**Issue by calmrat** [pyvec/cz.pycon.org-2016#89]
Send reports to ALL sponsors about how the event went.

**Comment by calmrat** [comment]
Reporting: 
After the event, ... would appreciate a follow-up report emailed to .... If there will be pictures, please share them and we can possibly discuss doing a blog post after the event.

**Comment by tricoder42** [comment]
@kejbaly2 Are you going to do this? Photos are already available bit.ly/PyConCZ2016-photos

**Comment by calmrat** [comment]
Yes, I'll take care of this. Just going to take me longer than I'd like it
too...

-Chris

**Comment by calmrat** [comment]
draft posted

https://docs.google.com/document/d/1kO2rVeh1AsFYFeSnVI6UGoiSOvM9fhFGOUkMhTU-Ls0/edit

**Comment by encukou** [comment]
http://blog.python.cz/pycon-cz-conference-wrap-up-summary
