### ISSUE TITLE
Catering - Tea

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2016#9]
This year we provided coffee and it was a huge success. We'll definitely contact the same vendor next year.

However, not everybody likes coffee. What if we also provide a tea catering?
# Call to action

Find a tea provider (probably some tea saloons in Brno), ask them if it's possible, figure out how tea would be served (paper cups or ceramic ones) and get price estimate.

**Comment by calmrat** [comment]
We could ask the coffee provider to also do this, no?

**Comment by tricoder42** [comment]
Managed by our coffee provider
