### ISSUE TITLE
Sponsored by section of landing page

### ISSUE THREAD

**Issue by calmrat** [pyvec/cz.pycon.org-2016#91]
We're starting to pick up sponsors, which means we need to start adding them to the site.

**Comment by calmrat** [comment]
PSF logo and official description : https://wiki.python.org/psf/PSF%20Press%20Kit

**Comment by calmrat** [comment]
@tricoder42 hey, i've added the first round of data to the admin panel db

I suppose we could replace the existing 'want to sponsor page' with actual 'PyConCZ sponsors' page and just put a link to the pdf and say 'see here if you're interested in sponsoring PyCon CZ'

[PyConCZ 2016 Sponsorship Prospectus .pdf](https://github.com/pyvec/cz.pycon.org-2016/files/478599/PyConCZ.2016.Sponsorship.Prospectus.pdf)

I think by this time we've reached out to all the potential sponsors... and shared the info via pdf with them all anyway.

**Comment by calmrat** [comment]
@beatrix-bodo @tricoder42 when do you think the sponsors page will be ready? I would consider this high priority, since several have already posted money to us... 

Thanks

**Comment by tricoder42** [comment]
Done already
