### ISSUE TITLE
wrong twitter handle for Kátia Nakamura team member

### ISSUE THREAD

**Issue by kvbik** [pyvec/cz.pycon.org-2016#95]
on team page [1] Kátia Nakamura does not have correct twitter handle.

[1] https://cz.pycon.org/2016/about/team

thx for the report to Vojta Roček [2]

[2] https://www.linkedin.com/in/vojtarocek

**Comment by kvbik** [comment]
i think it should be https://twitter.com/katianakamura instead of https://twitter.com/katiayn

**Comment by kvbik** [comment]
i think it should be https://twitter.com/katianakamura instead of https://twitter.com/katiayn

**Comment by kvbik** [comment]
i think it should be https://twitter.com/katianakamura instead of https://twitter.com/katiayn

**Comment by tricoder42** [comment]
Fixed, thank you for report!
