### ISSUE TITLE
Add venue info to the site

### ISSUE THREAD

**Issue by calmrat** [pyvec/cz.pycon.org-2016#97]
Someone wrote me and mentioned the site doesn't actually mention where the event will be.

"Is the event going to take place in FIT (Bozetechova)?" they said... "Bug report: it is
not mentioned on the page at all."

Might want to add that somewhere on the site to make it clear.

**Comment by kvbik** [comment]
+1 on this.. i was trying to show it to some Brno people this weekend too.. did not find.

**Comment by tricoder42** [comment]
Done already
